// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnchorLink: typeof import('./src/demo/AnchorLink.vue')['default']
    BlogHeader: typeof import('./src/components/BlogHeader.vue')['default']
    BlogMain: typeof import('./src/components/BlogMain.vue')['default']
    BlogMenu: typeof import('./src/components/BlogMenu.vue')['default']
    Counter: typeof import('./src/demo/Counter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleOfContent: typeof import('./src/components/TitleOfContent.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
